[package]
name = "ic-stable-memory"
version = "0.2.3"
authors = ["Александр Втюрин <senior.joinu@gmail.com>"]
edition = "2021"
description = "Internet Computer's stable memory collections and tools"
license = "MIT"
readme = "./README.md"
keywords = ["dfinity", "internet-computer", "ic", "stable-memory", "collections"]

[lib]
path = "./src/lib.rs"

[dependencies]
ic-cdk = "0.6.1"
speedy = "0.8.3"
candid = "0.8.3"
serde = "1.0.146"
num-bigint = "0.4.3"
copy_as_bytes = "0.1.1"