[package]
name = "ic-stable-memory"
version = "0.1.0"
authors = ["Александр Втюрин <senior.joinu@gmail.com>"]
edition = "2021"
description = "Internet Computer's stable memory collections and tools"
license = "MIT"
readme = "../README.md"
keywords = ["dfinity", "internet-computer", "ic", "stable-memory", "memory", "collections"]

[lib]
path = "./src/lib.rs"

[dependencies]
ic-cdk = { path = "../cdk-rs/src/ic-cdk" }
candid = { path = "../candid/rust/candid" }
serde = "1.0.136"